# Generated by Django 3.2.7 on 2022-11-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinsapp', '0002_alter_pin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='image',
            field=models.ImageField(default='media/', upload_to='pins'),
            preserve_default=False,
        ),
    ]
